import { IDropdownSelectOption } from "../../components/dropdownSelect";

export const intlLanguages: IDropdownSelectOption[] = [
    { value: "English", label: "English - en" },
    { value: "Arabic", label: "Arabic - ar" },
    { value: "Spanish", label: "Spanish - es" },
    { value: "French", label: "French - fr" },
    { value: "Russian", label: "Russian - ru" },
    { value: "Portuguese", label: "Portuguese - pt" },
    { value: "Turkish", label: "Turkish - tr" },
    { value: "Polish", label: "Polish - pl" },
    { value: "Vietnamese", label: "Vietnamese - vi" },
    { value: "German", label: "German - de" },
    { value: "Italian", label: "Italian - it" },
    { value: "Indonesian", label: "Indonesian" },
    { value: "Chinese", label: "Chinese - zh" },
    { value: "Thai", label: "Thai - th" },
    { value: "Dutch", label: "Dutch" },
    { value: "Romanian", label: "Romanian - ro" },
    { value: "Ukrainian", label: "Ukrainian - uk" },
    { value: "Hungarian", label: "Hungarian - hu" },
    { value: "Korean", label: "Korean - ko" },
    { value: "Uzbek", label: "Uzbek" },
    { value: "Czech", label: "Czech" },
    { value: "Japanese", label: "Japanese" },
    { value: "Swedish", label: "Swedish" },
    { value: "Hindi", label: "Hindi" },
    { value: "Burmese", label: "Burmese" },
    { value: "Greek", label: "Greek" },
    { value: "Central Khmer", label: "Central Khmer" },
    { value: "Hebrew", label: "Hebrew" },
    { value: "Azerbaijani", label: "Azerbaijani" },
    { value: "Slovak", label: "Slovak" },
    { value: "Danish", label: "Danish" },
    { value: "Bengali", label: "Bengali" },
    { value: "Croatian", label: "Croatian" },
    { value: "Bulgarian", label: "Bulgarian" },
    { value: "Serbian", label: "Serbian" },
    { value: "Georgian", label: "Georgian" },
    { value: "Malay", label: "Malay" },
    { value: "Persian", label: "Persian" },
    { value: "Norwegian Bokmål", label: "Norwegian Bokmål" },
    { value: "Finnish", label: "Finnish" },
    { value: "Catalan", label: "Catalan" },
    { value: "Lithuanian", label: "Lithuanian" },
    { value: "Amharic", label: "Amharic" },
    { value: "Gujarati", label: "Gujarati" },
    { value: "Latvian", label: "Latvian" },
    { value: "Bosnian", label: "Bosnian" },
    { value: "Slovenian", label: "Slovenian" },
    { value: "Lao", label: "Lao" },
    { value: "Urdu", label: "Urdu" }
];



export const fileTypes: IDropdownSelectOption[] = [
    { value: "text", label: "text" },
    { value: "json", label: "json" },
    { value: "yaml", label: "yaml" },
];
